apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-exporter
  namespace: lens-metrics
spec:
  selector:
    matchLabels:
      app: gcp-exporter
  template:
    metadata:
      labels:
        app: gcp-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9118"
    spec:
      containers:
      - name: application
        image: norbega/gcp-status-exporter:v1.1.0
        resources:
          limits:
            memory: "64Mi"
            cpu: "50m"
        env:
          - name: PYTHONUNBUFFERED
            value: "True"
          - name: MANAGE_ALL_EVENTS 
            value: "True"
          - name: DEBUG
            value: "True"
          - name: LAST_UPDATE
            value: "True"
        ports:
        - containerPort: 9118
