apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-exporter
spec:
  selector:
    matchLabels:
      app: gcp-exporter
  template:
    metadata:
      labels:
        app: gcp-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9118"
    spec:
      containers:
      - name: application
        image: norbega/gcp-status-exporter:v2.0.0-rc1
        resources:
          limits:
            memory: "64Mi"
            cpu: "50m"
        ports:
        - containerPort: 9118
