{
 "title": "Google Cloud Platform - Incident status",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Products With Related Issues",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (product) (gcp_incidents) > 0",
     "legendFormat": "{{ product }}"
    }
   ]
  },
  {
   "title": "Product Incident Ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (product) (rate(gcp_incidents[1m]))",
     "legendFormat": "{{ product }}"
    }
   ]
  },
  {
   "title": "Current Issues",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "expr": "gcp_incidents > 0" }
   ]
  }
 ]
}